name: Deploy to environments

on:
  push:
    branches:
    - main

jobs:
  train-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job.yml --resource-group rg-ml-challenge --workspace-name aml-ml-challenge --stream

  train-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
    needs: train-dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/prod-job.yml --resource-group rg-ml-challenge --workspace-name aml-ml-challenge --stream
