name: trigger on pull request

on: [pull_request]

jobs:
  train:
    name: linting-testing
    runs-on: ubuntu-latest
    steps:
    # - name: Placeholder
    #   run: |
    #     echo "Will add code checks here in next challenge"
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install Flake8
      run: |
        python -m pip install flake8
    - name: Run linter
      run: | 
        flake8 src/model/
    - name: Install requirements
      run: |
        python -m pip install -r requirements.txt
    - name: Run tests
      run: | 
        pytest tests/

